name = "MARS"
uuid = "b2b8a7f1-da70-4e5f-beaa-e2774ec39c2f"
authors = ["Mateusz Dadej"]
version = "1.0.0-DEV"

[compat]
julia = "1"

[extras]
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Test"]
